### ISSUE TITLE
how to use in Ionic 3 app

### ISSUE THREAD

**Issue by Lokeai** [DavidBriglio/cordova-plugin-foreground-service#1]
Hello,

This is not an issue related to the plugin, but I am having a trouble to use this plugin in ionic 3 app. 
Could anybody share an example how to use this plugin in ionic 3 app, please?

Thanks

**Comment by Lokeai** [comment]
I am trying to do `(<any>window).plugins.foregroundService.start('GPS Running', 'Background Service')` in my app.component.ts but on android studio console getting ERROR

**Comment by Lokeai** [comment]
I have tried `cordova.plugins.foregroundService.start('GPS Running', 'Background Service', 'myicon', 3, 10)` but getting undefined

**Comment by DavidBriglio** [comment]
Hello, if you are getting an error please show the exact output. Does your app meet the requirements in the readme?
```
cordova version >= 8.0.0
cordova-android version >= 7.0.0
android-sdk api >= 26
```
If your app does not meet these requirements, the plugin will not be present in the app and may be why you are getting undefined.

Thank you for using the plugin!

**Comment by DavidBriglio** [comment]
@Lokeai Has there been any update on this?

**Comment by DavidBriglio** [comment]
Please re-open this issue if you are still experiencing this problem.

**Comment by marckassay** [comment]
Here is a pending ionic-native [PR](https://github.com/ionic-team/ionic-native/pull/3017) for it.
