### ISSUE TITLE
Example of local notifications implemented ?

### ISSUE THREAD

**Issue by wa05** [DavidBriglio/cordova-plugin-foreground-service#11]
Hi ! Excuse me for being annoying but I'm confused and with not much experience with Cordova / Android..

I cant difference this with :
https://github.com/katzer/cordova-plugin-background-mode

I want to show local notifications after receiving an event from Wamp.js (my notification server...)
But I cant with the app closed.. any idea on how to implement this..  or if this is the correct plugin to do that.. thanks !

**Comment by DavidBriglio** [comment]
No problem! Is your app in the background, or is it completely closed (killed process)?

**Comment by wa05** [comment]
Solved with FCM and Phonegap Push Plugin ! ..
