### ISSUE TITLE
Which plugin should we use to run javascript code in background?

### ISSUE THREAD

**Issue by FreePhoenix888** [DavidBriglio/cordova-plugin-foreground-service#24]
> NOTE: This plugin does not on its own allow the user to execute javascript while the app is in the background

**Comment by FreePhoenix888** [comment]
@DavidBriglio @dpeacock

**Comment by DavidBriglio** [comment]
There are many plugins that allow you to run in the background, maybe start here:
https://github.com/katzer/cordova-plugin-background-mode

**Comment by FreePhoenix888** [comment]
> There are many plugins that allow you to run in the background, maybe start here: https://github.com/katzer/cordova-plugin-background-mode

I have seen that plugin and I am not sure it allows me to let my apollo subscription to work all the time
