### ISSUE TITLE
Can you please change the minimum platform to 5.0.0

### ISSUE THREAD

**Issue by alexhisen** [DavidBriglio/cordova-plugin-foreground-service#5]
i.e. in plugin.xml instead of
engine name="cordova-android" version=">=7.0.0"
change to
engine name="cordova-android" version=">=5.0.0"
Although cordova-android older than 6.3 defaults to android-23, 24 or 25 and this plugin needs 26, it's possible to use older cordova-android platform (at least as old as 5.x) and manually specify which SDK level you want to compile against with target=android-26 in project.properties.
We've tested this plugin and it works just fine with cordova-android 5.2.2.

**Comment by DavidBriglio** [comment]
According to the support table [here](https://cordova.apache.org/docs/en/latest/guide/platforms/android/#requirements-and-support) API level 26 is only supported on 6.X.X and above. How did you run your tests on 5.2.2? Did you test from a clean install of both cordova and cordova-android?

**Comment by alexhisen** [comment]
We never upgraded from 5.x to newer cordova-android

**Comment by DavidBriglio** [comment]
I will not be lowering the requirement to 5.X since the documentation shows that 6.X is the earliest version that is compatible with android API 26. I will review to see if 6.X will work as intended as well.
