### ISSUE TITLE
Docs should probably mention that execution stops a few minutes after screen turns off

### ISSUE THREAD

**Issue by alexhisen** [DavidBriglio/cordova-plugin-foreground-service#6]
You still need something like https://github.com/boltex/cordova-plugin-powermanagement (with dim() and setReleaseOnPause(false)) in addition to this plugin to keep your code running when user turns off screen. And even then, it'll only run if phone is plugged into power.

**Comment by spiritonline** [comment]
He Alexhisen,

We are trying to find a solution where we can play an alert sound that is triggered by a bluetooth peripheral. Timing of that trigger is variable so we need the app to process the alert and sound the alarm while in the background, on battery power with the screen off. 
Would you have any pointers as to how we can achieve this?

**Comment by alexhisen** [comment]
This can most likely be done under iOS. You can learn more about what you need to do in my write up here:
https://github.com/randdusing/cordova-plugin-bluetoothle/issues/433

Latest Android supports something similar (i.e. broadcasting an event on BLE packet) but I am not aware of any cordova plugin that takes advantage of these new APIs yet.

**Comment by DavidBriglio** [comment]
Please check my documentation update and verify if you are properly utilizing the plugin: 7fdf84ba8754425dbf96d9463c4eef24d44ddb42

**Comment by DavidBriglio** [comment]
What you may be experiencing here is in the [Android documentation](https://developer.android.com/about/versions/oreo/background#services):

> While an app is in the foreground, it can create and run both foreground and background services freely. When an app goes into the background, it has a window of several minutes in which it is still allowed to create and use services. At the end of that window, the app is considered to be idle.

This plugin starts a foreground service so that your application is considered a "foreground app", which will let you use background services that you create freely, and prevents this behaviour. It does not by itself keep the application running in the background.

**Comment by alexhisen** [comment]
I would still mention explicitly using something like https://github.com/boltex/cordova-plugin-powermanagement (with dim() and setReleaseOnPause(false)). When most developers think of running in the background, they think it will continue when screen is turned off, which it won't without that extra plugin. Unlike say https://github.com/katzer/cordova-plugin-background-mode which does the same thing as your plugin (only with a lot more stuff) but it does set the SCREEN_DIM_WAKE_LOCK.
