### ISSUE TITLE
Cordova version

### ISSUE THREAD

**Issue by UlisesCeca** [DavidBriglio/cordova-plugin-foreground-service#7]
Hi, Is it possible to make this plugin compatible with cordova 7.1.0 and cordova-android 6.3.0?

Thanks.

**Comment by DavidBriglio** [comment]
I will do some testing to see if this is an option. According to the documentation cordova-android 6.X.X should support sdk 26 which is required for this plugin. Have you done any testing on this setup?

**Comment by UlisesCeca** [comment]
when adding the plugin to my 7.1.0 cordova project it says that minimum version required of cordova is 8.0.0 and then it doesn't get installed

**Comment by alexhisen** [comment]
You can use this fork: https://github.com/alexhisen/cordova-plugin-foreground-service

**Comment by DavidBriglio** [comment]
I am removing the cordova version requirement, this will be up to the user to manage.

**Comment by DavidBriglio** [comment]
Version 1.1.2 will now work with any cordova version.
